Add REACT_APP_STORE_ADDRESS for fast loading
corp-momenti/metaplex pull request #2
Opened 2022-01-11 02:54 UTC by sglim

2022-01-11 03:46 UTC, rudebono approved these changes

2022-01-11 05:05 UTC, rudebono requested changes
https://github.com/corp-momenti/metaplex/blob/2a17c1c6447c5ebfdab558a39b3ec09748a32f67/js/packages/web/next.config.js#L34

- REACT_APP_STORE_ADDRESS (X)
- STORE_ADDRESS (O)

STORE_ADDRESS 를 미리 지정하면 이론상 로딩을 빠르게 할 수 있지만,
실제 적용하면 버그로 인해 정상 작동하지 않습니다.

2022-01-11 08:54 UTC, sglim commented
헐 플라시보였던 거였나요...

2022-01-11 08:54 UTC, sglim commented
근데 원래 리액트에서 환경변수 적용할 때 저렇게 하는게 맞을텐데 왜 버그라고 생각하시는 건가요?

2022-01-17 11:05 UTC, sglim commented
업데이트 된 버전에는 없는 필드라 close 합니다.

2022-01-17 11:05 UTC, closed without merging